"""The engine's contracts: every type crossing a module boundary.

Leaf rule: this package imports nothing from the project, and only pydantic
plus the standard library from outside.
"""

from .base import (
    SCHEMA_VERSION,
    BriefHash,
    ConfigHash,
    FrozenDict,
    GraphHash,
    HashDigest,
    Identifier,
    NonEmptyStr,
    NonNegativeInt,
    PersonaId,
    PopulationHash,
    PositiveInt,
    RunId,
    SignedUnitInterval,
    SimBaseModel,
    StimulusId,
    UnitInterval,
    canonical_hash,
    canonical_json,
    canonical_payload,
)
from .brief import (
    Assumption,
    AttributeId,
    Audience,
    BriefPack,
    CategoryOntology,
    Claim,
    ClaimId,
    Competitor,
    CompletionPolicy,
    CurrencyCode,
    Evidence,
    OrdinalBand,
    OrdinalScale,
    Price,
    Product,
    ProductBrief,
)
from .enums import ClaimSource, FieldOrigin, PersonaFieldDomain
from .errors import BudgetExhausted, GateFailure, SchemaVersionError, SimError
from .persona import AttributeValue, EmbeddingRef, Persona, PersonaSource

__all__ = [
    "Assumption",
    "AttributeId",
    "AttributeValue",
    "Audience",
    "BriefPack",
    "BudgetExhausted",
    "BriefHash",
    "CategoryOntology",
    "Claim",
    "ClaimId",
    "ClaimSource",
    "CompletionPolicy",
    "Competitor",
    "ConfigHash",
    "CurrencyCode",
    "EmbeddingRef",
    "Evidence",
    "FieldOrigin",
    "FrozenDict",
    "GateFailure",
    "GraphHash",
    "HashDigest",
    "Identifier",
    "NonEmptyStr",
    "NonNegativeInt",
    "OrdinalBand",
    "OrdinalScale",
    "Persona",
    "PersonaFieldDomain",
    "PersonaId",
    "PersonaSource",
    "PopulationHash",
    "PositiveInt",
    "Price",
    "Product",
    "ProductBrief",
    "RunId",
    "SCHEMA_VERSION",
    "SchemaVersionError",
    "SignedUnitInterval",
    "SimBaseModel",
    "SimError",
    "StimulusId",
    "UnitInterval",
    "canonical_hash",
    "canonical_json",
    "canonical_payload",
]
